### ISSUE TITLE
unknown type name 'SyntaxTokens'

### ISSUE THREAD

**Issue by sonu628** [PawanKartikS/Berry#11]
upon building the repo by the command 
`make && make clean`
I get the following output
```
clang++ -std=c++17 ArgParser.cpp -c
In file included from ArgParser.cpp:4:
In file included from ./ArgParser.h:6:
In file included from ./AST.h:6:
In file included from ./Parse.h:14:
./Token.h:53:36: error: unknown type name 'SyntaxTokens'
  explicit SyntaxTokenstream(const SyntaxTokens &syntaxTokens);
                                   ^
1 error generated.
make: *** [all] Error 1
```

i searched for the type SyntaxTokens inside the repo
```
~/Documents/Berry master ❯ grep 'SyntaxTokens' *                       15:13:49
grep: Bin: Is a directory
Token.cpp:SyntaxTokenstream::SyntaxTokenstream(const SyntaxTokens &syntaxTokens) {
Token.cpp:SyntaxTokenstream::consume(void) {
Token.cpp:bool SyntaxTokenstream::isEmpty(void) { return _stream.empty(); }
Token.cpp:Token::Kind SyntaxTokenstream::peek(void) {
Token.cpp:unsigned long SyntaxTokenstream::size(void) {
Token.h:struct SyntaxTokenstream {
Token.h:  explicit SyntaxTokenstream(const SyntaxTokens &syntaxTokens);
```
but did not found any declaration

clang version - 
```
~/Documents/Berry master ❯ clang --version                             15:15:17
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
````
Operating System used - MacOS Catalina 10.15

**Comment by PawanKartikS** [comment]
Thanks for opening the issue!

`SyntaxTokens` is a typedef which you can find in `Signatures.h`. I'm currently rewriting the parser which that uses `SyntaxTokenStream` (see `Token.cpp`) to better parse the syntax (this should also fix some parsing-related bugs).

Agree that the current build is broken. Next commit will address this.

**Comment by PawanKartikS** [comment]
I'm sorry for leaving this issue opened for so long. I've just updated the repo. It should compile fine now. Please look at the `Readme` for general info. I'm aware of some minor parsing bugs and missing features. Next 2-3 commits to the master branch should fix or implement them. I'm right now working on writing the test cases. Feel free to browse the codebase, open any more issues or submit PRs.
